[package]
name = "merutos"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/MlUlM/merutos"

[workspace]
members = [
    "merutos_common"
]

[dependencies]
tar = "0.4.40"
merutos_common = {path = "./merutos_common"}