[package]
name = "meltos"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/MlUlM/meltos"

[workspace]
members = [
    "meltos_common",
    "meltos_server"
]

[dependencies]
tar = "0.4.40"
meltos_common = {path = "meltos_common" }


[workspace.dependencies]
async-trait = "0.1.74"
tokio = {version = "1.34.0", features = ["full"]}