# roomの最大生存期間
# ユーザーがroomをopenする際にlife_time_secを指定していない場合はこの値が反映される
# ユーザーが指定していた場合、この設定値を超えていない場合はユーザーの生存期間が反映され、超えている場合は設定値が反映される。
# 24H
room_limit_life_time_sec = 86400

# openやpushの際に渡されるbundleの最大サイズ
# objsのバッファの合計サイズを元に計算される
# 100MIB
limit_bundle_size = 104857600

# TVCのリポジトリの最大サイズ
# bundleがpushされる際にリポジトリサイズが許容値を超えないかを確認するために使用される。
# リポジトリサイズは.meltos/objs内のバッファサイズの合計値
# 1GIB
limit_tvc_repository_size = 1073741824
