# roomの最大生存期間
# ユーザーがroomをopenする際にlifetime_secsを指定していない、またはこの上限値を超えた場合場合はこの値が反映される。
# 24H
room_limit_life_time_sec = 86400


# openやpushの際に渡されるbundleの最大サイズ
# objsのバッファの合計サイズを元に計算される
# 1MIB
limit_bundle_size = 1024

# TVCのリポジトリの最大サイズ
# bundleがpushされる際にリポジトリサイズが許容値を超えないかを確認するために使用される。
# リポジトリサイズは.meltos/objs内のバッファサイズの合計値
# 4MIB
limit_tvc_repository_size = 3072


# ルームの定員の上限値
# ユーザーがroomをopenする際にuser_limitsを指定していない、またはこの上限値を超えた場合はこの値が反映される
max_user_limits = 100