[package]
name = "meltos_tui"
version = "0.1.0"
edition = "2021"


[dependencies]
ratatui = "0.24.0"
crossterm = "0.27.0"
meltos_core = { path = "../../crates/meltos_core" }
meltos_thread = { path = "../../crates/meltos_thread" }