[package]
name = "meltos_client"
version = "0.1.0"
edition = "2021"


[dependencies]
meltos = { path = "../meltos" }


anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }