[package]
name = "meltos_git"
version = "0.1.0"
edition = "2021"


[dependencies]
sha1_smol = "1.0.0"
meltos_util = { path = "../meltos_util" }
anyhow = { workspace = true }
thiserror = { worspace = true }
serde = { workspace = true }