[package]
name = "meltos"
version = "0.1.0"
edition = "2021"


[dependencies]
bincode = "1.3.3"
uuid = { version = "1.6.1", features = ["v4"] }
meltos_core = { path = "../meltos_core" }
serde = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }