[package]
name = "meltos_tvn"
version = "0.1.0"
edition = "2021"


[dependencies]
meltos_util = { path = "../meltos_util" }

auto-delegate = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }