[package]
name = "meltos_util"
version = "0.1.0"
edition = "2021"


[dependencies]
bincode = "1.3.3"
flate2 = { version = "1.0.28" }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
meltos_macros = { path = "../meltos_macros" }