@startuml
'https://plantuml.com/object-diagram

package リプライ{
    object リプライリスト{

    }
}


package メッセージ{
    object メッセージリスト{
        メッセージカラムのリスト
    }

    object メッセージカラム{
        メッセージID
        メッセージ
    }

    object メッセージ{
        ユーザー名
        テキスト
    }


    メッセージリスト "0..n" -down-> メッセージカラム
    メッセージカラム -down-> "1" メッセージ
}

@enduml
