openapi: "3.0.2"
info:
  title: Room Api
  version: "1.0"
servers:
  - url: "https://meltos/room/"
paths:
  /open:
    description: "Roomを新規作成します。"
    post:
      responses:
        '200':
          description: OK
