name: deploy
run-name: ${{ github.actor }} is deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_DIR: ${{ secrets.SERVER_DEPLOY_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: deploy
        run:  |
          cd ${DEPLOY_DIR}
          sudo git pull
          cargo build --release --jobs 1
          sudo systemctl restart meltos.service
